name: Combine CSV Files

on:
  workflow_dispatch:

jobs:
  combine-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --use-pep517 -r requirements.txt

      - name: Set up Google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json

      - name: Run combine script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          set -e
          python combine.py

      - name: Upload combined CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-csv
          path: waffle_house.csv
