name: Run Scraper, Combine, Upload, and Map

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  daily_process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt plotly pandas google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Set up Google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json

      - name: Run the scraper and upload script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python web_scrape.py

      - name: Combine new CSV, upload, and generate map
        run: python combine.py