name: Run Scraper and Upload to Google Drive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at 6pm central (midnight UTC) every day

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Clear pip cache
      run: |
        pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --use-pep517 -r requirements.txt

    - name: Set up Google credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json

    - name: Run the scraper and upload script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python web_scrape.py